### ISSUE TITLE
Double Appearance on Job Priority

### ISSUE THREAD

**Issue by AttackHelicopter6784** [andrej-hajduk/XRF-13#26]
All jobs except for Xenomorph Queen and standard Xenomorph are doubled, but still linked. If you change one of the squad leaders to high, they both become high, etc. 
<img width="449" alt="Capture" src="https://user-images.githubusercontent.com/62526666/123556574-f35dbd00-d759-11eb-89f9-bf032bfd3334.PNG">

**Comment by ghost** [comment]
#7 testmerged during this.
